name: Build and Deploy OCaml Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OCaml and Dune
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.2.0'
          dune-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap darcs g++-multilib gcc-multilib mercurial musl-tools rsync

      - name: Install dependencies
        run: opam install odoc

      - name: Build documentation
        run: dune build @doc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _build/default/_doc/_html
